### ISSUE TITLE
Need FSUIDs for people registering with non-FSU emails

### ISSUE THREAD

**Issue by Hachimaki** [FSU-ACM/Contest-Server#21]
Based on a user email, it seems like users have no means of adding FSUIDs to the profile, or don't think to do it, but only if they register with a personal or non-FSU email.  We need a process to prompt users who either were quick registered or register with personal emails to fill our their profiles with FSUID so we can accurately add them to extra credit.  Perhaps we should send users who are quick registered or don't use FSU emails a confirmation link to fill out their profiles?

**Comment by andrewsosa** [comment]
This will be address via #20
