### ISSUE TITLE
FAQ button doesn't scroll to FAQ section

### ISSUE THREAD

**Issue by manterolat** [FSU-ACM/Contest-Server#74]
Currently pressing the FAQ button on the navbar redirects to the index page, but does not scroll down to the FAQ section. It seems the FAQ section is missing an id.

**Comment by andrewsosa** [comment]
Good catch -- I was actually aware of this but forgot to fix it and/or make an issue. I think all it need is adding a `id='faq'` (whatever matches the navbar template component) to the header on the `index.html` template.
